apiVersion: v1
kind: Pod
metadata:
 name: backend-service
 labels:
  app.kubernetes.io/name: "backend"
  app.kubernetes.io/component: "service"
  app.kubernetes.io/environment: "production"
  app.kubernetes.io/version: "v1.0"
spec:
 containers:
  - name: main-container
    image: nginx:alpine
    resources:
     requests:
      cpu: "100m"
      memory: "64Mi"
     limits:
      cpu: "400m"
      memory: "128Mi"
    ports:
     - containerPort: 80
    livenessProbe:
     httpGet:
      path: /
      port: 80
     initialDelaySeconds: 30
     periodSeconds: 10
---
apiVersion: v1
kind: Pod
metadata:
 name: frontend-service
 labels:
  app.kubernetes.io/name: "frontend"
  app.kubernetes.io/component: "service"
  app.kubernetes.io/environment: "production"
  app.kubernetes.io/version: "v1.0"
spec:
 containers:
  - name: main-container
    image: nginx:alpine
    resources:
     requests:
      cpu: "100m"
      memory: "64Mi"
     limits:
      cpu: "400m"
      memory: "128Mi"
    ports:
     - containerPort: 80
    livenessProbe:
     httpGet:
      path: /
      port: 80
     initialDelaySeconds: 30
     periodSeconds: 10
---
apiVersion: v1
kind: Pod
metadata:
 name: logging-service
 labels:
  app.kubernetes.io/name: "logging"
  app.kubernetes.io/component: "utility"
  app.kubernetes.io/version: "v2.0"
spec:
 containers:
  - name: log-collector
    image: busybox
    command:
     - /bin/sh
     - -c
     - while true; do echo $(date) ' - Collecting logs'; sleep 5; done
    resources:
     requests:
      cpu: "50m"
      memory: "16Mi"
     limits:
      cpu: "200m"
      memory: "32Mi"
    volumeMounts:
     - name: log-volume
       mountPath: /var/log
 volumes:
  - name: log-volume
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
 name: monitoring-service
 labels:
  app.kubernetes.io/name: "monitoring"
  app.kubernetes.io/component: "utility"
  app.kubernetes.io/version: "v2.3"
spec:
 containers:
  - name: metrics-collector
    image: busybox
    command:
     - /bin/sh
     - -c
     - while true; do echo $(date) ' - Collecting metrics'; sleep 5; done
    resources:
     requests:
      cpu: "50m"
      memory: "16Mi"
     limits:
      cpu: "200m"
      memory: "32Mi"
    volumeMounts:
     - name: metrics-volume
       mountPath: /var/metrics
 volumes:
  - name: metrics-volume
    emptyDir: {}
# kubectl get pods --show-labels
# kubectl get pods --selector app.kubernetes.io/environment=production,app.kubernetes.io/component=service
# kubectl get pods -L app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/environment,app.kubernetes.io/version
