apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql
spec:
 serviceName: mysql
 replicas: 3
 selector:
  matchLabels:
   app: mysql
 template:
  metadata:
   labels:
    app: mysql
  spec:
   containers:
    - name: mysql
      image: mysql:8.0
      ports:
       - containerPort: 3306
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: "root"
      volumeMounts:
       - name: mysql-data
         mountPath: /var/lib/mysql
       - name: mysql-init
         mountPath: /docker-entrypoint-initdb.d
   volumes:
    - name: mysql-init
      configMap:
       name: mysql-config
 volumeClaimTemplates:
  - metadata:
     name: mysql-data
    spec:
     accessModes: ["ReadWriteOnce"]
     resources:
      requests:
       storage: 1Gi
     storageClassName: standard
