apiVersion: apps/v1
kind: ReplicaSet
metadata:
 labels:
  app: myapp
 name: myapp
spec:
 replicas: 3
 selector:
  matchLabels:
   app: myapp
 template:
  metadata:
   labels:
    app: myapp
  spec:
   containers:
    - name: web
      image: my-nest-app:latest
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 3000
