apiVersion: v1
kind: Pod
metadata:
 name: demo
spec:
 volumes:
  - name: emptydir-volume
    emptyDir: {}
  - name: nfs-volume
    nfs:
     server: 172.20.188.198
     path: /mnt/shared
 containers:
  - name: main-container
    image: nginx:alpine
    resources:
     requests:
      cpu: "100m"
      memory: "64Mi"
     limits:
      cpu: "400m"
      memory: "128Mi"
    volumeMounts:
     - name: emptydir-volume
       mountPath: /usr/share/nginx/html
     - name: nfs-volume
       mountPath: /mnt/nfs
    ports:
     - containerPort: 80
    livenessProbe:
     httpGet:
      path: /
      port: 80
     initialDelaySeconds: 30
     periodSeconds: 10
  - name: sidecar-container
    image: busybox
    command:
     [
      "/bin/sh",
      "-c",
      "while true; do echo $(date) ' - Sidecar logging'; sleep 5; done",
     ]
    resources:
     requests:
      cpu: "50m"
      memory: "16Mi"
     limits:
      cpu: "200m"
      memory: "32Mi"
    volumeMounts:
     - name: emptydir-volume
       mountPath: /nfs-share
