apiVersion: v1
kind: Pod
metadata:
 name: web-app01
 labels:
  app: "web-app"
spec:
 containers:
  - name: web
    image: nginx
    resources:
     requests:
      cpu: "100m"
      memory: "64Mi"
     limits:
      cpu: "400m"
      memory: "128Mi"
    ports:
     - containerPort: 80
    livenessProbe:
     httpGet:
      path: /
      port: 80
     initialDelaySeconds: 30
     periodSeconds: 10
---
apiVersion: v1
kind: Pod
metadata:
 name: web-app02
 labels:
  app: "web-app"
spec:
 containers:
  - name: web
    image: nginx
    resources:
     requests:
      cpu: "100m"
      memory: "64Mi"
     limits:
      cpu: "400m"
      memory: "128Mi"
    ports:
     - containerPort: 80
    livenessProbe:
     httpGet:
      path: /
      port: 80
     initialDelaySeconds: 30
     periodSeconds: 10
