apiVersion: apps/v1
kind: Deployment
metadata:
 name: release-name-weatherapp-ui
spec:
 replicas: 2
 selector:
  matchLabels:
   app.kubernetes.io/name: weatherapp-ui
 template:
  metadata:
   labels:
    app.kubernetes.io/name: weatherapp-ui
  spec:
   containers:
    - name: weatherapp-ui
      image: "afakharany/weatherapp-frontend:v3"
      imagePullPolicy: IfNotPresent
      env:
       - name: AUTH_HOST
         value: weatherapp-auth
       - name: AUTH_PORT
         value: "8080"
       - name: WEATHER_HOST
         value: weatherapp-weather
       - name: WEATHER_PORT
         value: "5000"
       - name: SECRET_KEY
         valueFrom:
          secretKeyRef:
           name: mysql-secret
           key: secret-key

      ports:
       - name: http
         containerPort: 3000
         protocol: TCP
      livenessProbe:
       httpGet:
        path: /health
        port: http
      readinessProbe:
       httpGet:
        path: /health
        port: http
