---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-weather
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: weatherapp-weather