kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: rbac-lab
 name: view-pods
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list", "watch", "create", "delete"]
